export const federalTaxes = 0.1;

export const states = {
  AL: { name: 'Alabama', stateTax: 0.05 },
  AK: { name: 'Alaska', stateTax: 0.0 },
  AZ: { name: 'Arizona', stateTax: 0.0259 },
  AR: { name: 'Arkansas', stateTax: 0.02 },
  CA: { name: 'California', stateTax: 0.1 },
  CO: { name: 'Colorado', stateTax: 0.0455 },
  CT: { name: 'Connecticut', stateTax: 0.03 },
  DC: { name: 'District of Columbia', stateTax: 0.04 },
  DE: { name: 'Delaware', stateTax: 0.022 },
  FL: { name: 'Florida', stateTax: 0.0 },
  GA: { name: 'Georgia', stateTax: 0.03 },
  HI: { name: 'Hawaii', stateTax: 0.032 },
  ID: { name: 'Idaho', stateTax: 0.031 },
  IL: { name: 'Illinois', stateTax: 0.0375 },
  IN: { name: 'Indiana', stateTax: 0.0323 },
  IA: { name: 'Iowa', stateTax: 0.0243 },
  KS: { name: 'Kansas', stateTax: 0.031 },
  KY: { name: 'Kentucky', stateTax: 0.05 },
  LA: { name: 'Louisiana', stateTax: 0.02 },
  ME: { name: 'Maine', stateTax: 0.058 },
  MD: { name: 'Maryland', stateTax: 0.0475 },
  MA: { name: 'Massachusetts', stateTax: 0.051 },
  MI: { name: 'Michigan', stateTax: 0.0425 },
  MN: { name: 'Minnesota', stateTax: 0.0535 },
  MS: { name: 'Mississippi', stateTax: 0.03 },
  MO: { name: 'Missouri', stateTax: 0.03 },
  MT: { name: 'Montana', stateTax: 0.02 },
  NE: { name: 'Nebraska', stateTax: 0.0351 },
  NV: { name: 'Nevada', stateTax: 0.0 },
  NH: { name: 'New Hampshire', stateTax: 0.0 },
  NJ: { name: 'New Jersey', stateTax: 0.014 },
  NM: { name: 'New Mexico', stateTax: 0.17 },
  NY: { name: 'New York', stateTax: 0.04 },
  NC: { name: 'North Carolina', stateTax: 0.0575 },
  ND: { name: 'North Dakota', stateTax: 0.011 },
  OH: { name: 'Ohio', stateTax: 0.0495 },
  OK: { name: 'Oklahoma', stateTax: 0.03 },
  OR: { name: 'Oregon', stateTax: 0.0475 },
  PA: { name: 'Pennsylvania', stateTax: 0.0307 },
  RI: { name: 'Rhode Island', stateTax: 0.0375 },
  SC: { name: 'South Carolina', stateTax: 0.03 },
  SD: { name: 'South Dakota', stateTax: 0.0 },
  TN: { name: 'Tennessee', stateTax: 0.0 },
  TX: { name: 'Texas', stateTax: 0.0 },
  UT: { name: 'Utah', stateTax: 0.0495 },
  VT: { name: 'Vermont', stateTax: 0.0335 },
  VA: { name: 'Virginia', stateTax: 0.03 },
  WA: { name: 'Washington', stateTax: 0.0 },
  WV: { name: 'West Virginia', stateTax: 0.03 },
  WI: { name: 'Wisconsin', stateTax: 0.0354 },
  WY: { name: 'Wyoming', stateTax: 0.04 },
};
